apiVersion: v1
kind: Service
metadata:
  name: piazza-service
  labels:
    app: piazza-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: piazza
  sessionAffinity: None